Suggested corrections: Chapter 6
bigskysoftware/hypermedia-systems pull request #15
Opened 2023-01-03 11:16 UTC by elliottinvent

2023-01-03 17:30 UTC, elliottinvent commented
Earlier I could see based on the Netlify PR deploy preview that the fixes I suggested for rendering "_hyperscript" in Asciidoc (`//_hyperscript`) hadn't worked, so I pushed a new commit to use a single backslash but that didn't work either.

I can't see any rhyme or reason as to why some instances of "_hyperscript" with a single backslash show fine and others don't – maybe it's a problem with the library you're using to render the Asciidoc to HTML? 

In my most recent commit I've used `+_hyperscript+` and this [seems to be working](https://deploy-preview-15--hypermedia-systems.netlify.app/) although my Sublime Text syntax helper doesn't recognise it. 

To me at least, the [Asciidoc guidance](https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/) on when to use `+` or `++` is as clear as mud, but this seems to be working!

2023-01-04 22:43 UTC, 1cg requested changes
holy smokes what an editing pass!  thank you!

i found one small edit to an edit, but otherwise looks great!

2023-01-04 22:43 UTC, 1cg commented on book/CH07_MorehtmxPatterns.adoc
> +that load time, nor is possible to cache the result.
"is it" probably?

2023-01-04 23:13 UTC, elliottinvent commented on book/CH07_MorehtmxPatterns.adoc
> +that load time, nor is possible to cache the result.
Yes, missed that one. Thanks!

2023-01-06 19:52 UTC, 1cg approved these changes

2023-01-06 19:55 UTC, merged

2023-01-06 19:55 UTC, 1cg commented
merged, thank you!